name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  # docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     -
  #       name: Login to Github Registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #     -
  #       name: Build and push
  #       uses: docker/build-push-action@v5
  #       with:
  #         push: true
  #         tags: ghcr.io/guftall/telegram-android-builder:latest
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: guftall/telegram-android-builder:latest
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          options: -v ${{ github.workspace }}:/var/www
          run: |
            ls /var/www
            bash docker-build.sh